basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = "basic_app"

urlpatterns = [
    path('registration/', views.register, name="register"),
    path('login/', views.user_login, name="login"),
]

learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name="index"),
    path('admin/', admin.site.urls),
    path('basic_app/', include("basic_app.urls")),
    path('logout/', views.user_logout, name="logout")
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional fields
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ("username", 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

basic_app/views.py
from django.shortcuts import render

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

from basic_app.forms import UserProfileInfoForm, UserForm

# Create your views here.


def index(request):
    return render(request, 'basic_app/index.html')


def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        user_profile_info_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and user_profile_info_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = user_profile_info_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, user_profile_info_form.errors)
    else:
        user_form = UserForm()
        user_profile_info_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html', context={'user_form': user_form,
                                                                   'profile_form': user_profile_info_form,
                                                                   'registered': registered})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('account is not active')
        else:
            print("login is failed")
            print('username: {}, password: {}'.format(username, password))
            return HttpResponse('invalid login')
    else:
        return render(request, 'basic_app/login.html', {})

templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title></title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <!-- Navbar/header -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="navbar-brand" href="{% url 'index' %}">Home Page</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basic_app:register' %}"
              >Registration Page</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin Page</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basic_app:login' %}"
              >Login Page</a
            >
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <!-- Main Block -->
    <div class="container">
      {% block body_block %}
      <!-- Anything outside will be inherited -->
      {% endblock %}
    </div>

    <!-- Footer -->
    <footer class="bg-light text-center text-lg-start">
      <!-- Copyright -->
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
        © 2020 Copyright:
        <a class="text-dark" href="https://mdbootstrap.com/">MDBootstrap.com</a>
      </div>
      <!-- Copyright -->
    </footer>
  </body>
</html>

templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}

{% block body_block %}

<div class="jumbotron">
    <h1 class="display-4">Django Level Five: Index Page</h1>
</div>

{% endblock %}

templates/basic_app/login.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}

{% block body_block %}

<div class="jumbotron">
    <h1 class="display-5">Django Level Five: Login Page</h1>

    <form method="post" action="{% url 'basic_app:login' %}">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username" placeholder="Enter username">
        <label for="password">Password</label>
        <input type="password" name="password">
        <input type="submit" value="Login">
    </form>
</div>

{% endblock %}

templates/basic_app/registration.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}

{% block body_block %}

<div class="jumbotron">
    <h1 class="display-5">Django Level Five: Registration Page</h1>

    {% if registered %}
    <p class="lead">Thank you for registration</p>
    {% else %}
    <p class="lead">Registration Form</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" value="Register">
    </form>
    {% endif %}
</div>

{% endblock %}